export const links = [
    {
        text: 'Home',
        path: '/home',
        active: true
    },
    {
        text: 'Trade',
        path: '/trade'
    },
    {
        text: 'Earn',
        path: '/earn'
    },
    {
        text: 'Contact',
        path: '/contact'
    },
]

export const whyChooseUs = [
    {
        image: '/briefcaseclosed.svg',
        heading: 'Proven Expertise',
        text: 'Our Copy Trader Masters have a track record of success, ensuring you gain from their experience and expertise.'
    },
    {
        image: '/briefcaseopen.svg',
        heading: 'Effortless Trading',
        text: 'No need for extensive research or strategy development replicate the trades of top traders and watch your investments grow.'
    },
    {
        image: '/keybig.svg',
        heading: 'Lucrative Referral Program',
        text: 'Earn commissions by inviting others to join Universal FX, adding an extra stream of income to your trading profits.'
    },
]

export const reviews = [
    {
        stars: 5,
        text: '"Universal FX makes trading accessible and profitable. The Copy Trader Masters do all the hard work, allowing me to earn without spending hours on research. Plus, the referral program is a great way to boost my income even further. Love it!"',
        image: '/emily.svg',
        name: 'Emily Davis 1'
    },
    {
        stars: 3,
        text: '"Universal FX makes trading accessible and profitable. The Copy Trader Masters do all the hard work, allowing me to earn without spending hours on research. Plus, the referral program is a great way to boost my income even further. Love it!"',
        image: '/adams.svg',
        name: 'Adam Lewis 2'
    },
    {
        stars: 2,
        text: '"Universal FX makes trading accessible and profitable. The Copy Trader Masters do all the hard work, allowing me to earn without spending hours on research. Plus, the referral program is a great way to boost my income even further. Love it!"',
        image: '/emily.svg',
        name: 'Adam Lewis 3'
    },
    {
        stars: 1,
        text: '"Universal FX makes trading accessible and profitable. The Copy Trader Masters do all the hard work, allowing me to earn without spending hours on research. Plus, the referral program is a great way to boost my income even further. Love it!"',
        image: '/adams.svg',
        name: 'Adam Lewis 4'
    },
    {
        stars: 2,
        text: '"Universal FX makes trading accessible and profitable. The Copy Trader Masters do all the hard work, allowing me to earn without spending hours on research. Plus, the referral program is a great way to boost my income even further. Love it!"',
        image: '/emily.svg',
        name: 'Adam Lewis 5'
    },
    {
        stars: 3,
        text: '"Universal FX makes trading accessible and profitable. The Copy Trader Masters do all the hard work, allowing me to earn without spending hours on research. Plus, the referral program is a great way to boost my income even further. Love it!"',
        image: '/adams.svg',
        name: 'Adam Lewis 6'
    },
    {
        stars: 4,
        text: '"Universal FX makes trading accessible and profitable. The Copy Trader Masters do all the hard work, allowing me to earn without spending hours on research. Plus, the referral program is a great way to boost my income even further. Love it!"',
        image: '/emily.svg',
        name: 'Adam Lewis 7'
    },
    {
        stars: 5,
        text: '"Universal FX makes trading accessible and profitable. The Copy Trader Masters do all the hard work, allowing me to earn without spending hours on research. Plus, the referral program is a great way to boost my income even further. Love it!"',
        image: '/adams.svg',
        name: 'Adam Lewis 8'
    },

]

export const questions = [
    {
        id: 1,
        heading: 'What is Copy Trading and how does it work with Universal FX?',
        content:
            'Copy Trading is a strategy that allows you to replicate the trades of experienced traders. At Universal FX, you grant authority to our Copy Trader Masters, who will trade on your behalf. Their trades are mirrored in your account, enabling you to benefit from their expertise and strategies without having to trade manually.',
        status: false,
    },
    {
        id: 2,
        heading: 'What types of income can I earn with Universal FX?',
        content:
            'With Universal FX, you can earn two types of income: Individual Earnings and Referral Commissions. Individual Earnings come from the profits generated by copying the trades of our expert traders. Referral Commissions are earned by referring others to the platform, with 10% commission on direct referrals and 5% on indirect referrals.',
        status: false,
    },
    {
        id: 3,
        heading: ' How do I start Copy Trading with Universal FX?',
        content:
            'Copy Trading is a strategy that allows you to replicate the trades of experienced traders. At Universal FX, you grant authority to our Copy Trader Masters, who will trade on your behalf. Their trades are mirrored in your account, enabling you to benefit from their expertise and strategies without having to trade manually.',
        status: false,
    },
]